language: cpp

os:
  - osx

compiler:
  - gcc
  #- clang

before_install:
  # macOS ->
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update         ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install SDL2   ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install GLEW   ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install ffmpeg ; fi

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
- make
